### ISSUE TITLE
Tools or libraries to parse PDDL at latest specification

### ISSUE THREAD

**Issue by padmalcom** [potassco/ipc-instances#2]
Hi thanks for the fantastic domain examples! This is not really an issue but a request for a recommendation or a tool or a library to parse the 2014 domain files.

I spent the last hour trying some libraries for python and java to parse and plan the example domains but all I tried failed.

**Comment by cjmuise-ibm** [comment]
Hey @padmalcom -- if you haven't seen the http://planning.domains/ initiative, it's probably worth having a look (contains these benchmarks and more).

If you'd like some direct advice on parsing things, I'd suggest heading to the [planning slack](https://the-planning-community.herokuapp.com/) and reaching out there (to me personally or in general). Lot's of support if you're looking for it.

Cheers!

**Comment by pluehne** [comment]
@cjmuise-ibm: Thanks for pointing @padmalcom in the right direction. I personally don’t know any parsing library I would recommend and that supports the entire feature set of PDDL as used in the 2014 International Planning Competition, but it’s also been a while since I last checked.

**Comment by cjmuise-ibm** [comment]
Again, we should have this conv on slack (right place for it!), but since the signup link appears to be broken currently (working on it), I'll point you here: https://github.com/boompig/pddl-parser-2

It's the one I typically go to, as it's fairly straight forward to extend to custom PDDL syntax. Grounding may be an issue, though.

If you really want something robust to the contest domains, then your best bet is to use contest-ready libraries. In particular, [this](http://hg.fast-downward.org/file/tip/src/translate) is the FastDownward translator, and it's common practice to start with that code base if you want to get things grounded smartly.

**Comment by pluehne** [comment]
All right. I’ll close this issue then and let you take the discussion to Slack.

**Comment by cjmuise-ibm** [comment]
Sign-ups should be working again: http://slack.planning.domains
