### ISSUE TITLE
Inconsistent Rovers Domain

### ISSUE THREAD

**Issue by pulkitverma25** [potassco/ipc-instances#5]
IPC 2006 Rovers PDDL domain has inconsistencies.
For eg:
```
(:action communicate_rock_data
 :parameters (?r - rover ?l - lander ?p - waypoint ?x - waypoint ?y - waypoint)
 :precondition (and (at ?r ?x)(at_lander ?l ?y)(have_rock_analysis ?r ?p)
                   (visible ?x ?y)(available ?r)(channel_free ?l)
            )
 :effect (and (not (available ?r))(not (channel_free ?l))(channel_free ?l)(communicated_rock_data ?p)(available ?r)
          )
)
```

Effect has both (not (channel_free ?l)) and (channel_free ?l).

**Comment by haz** [comment]
This is perfectly valid PDDL. The interpretation is that the positive effect prevails.

It exists to prevent communication occurring in a partial order plan between one action requiring the channel free and another creating that. It's a relic of compiling classical planning from temporal domains, and almost all planners would be fine with this.

**Comment by pulkitverma25** [comment]
My bad. I thought there's some inconsistency issue. With durative actions, it would've definitely made sense to me. I guess I should read more about compiling classical planning from temporal domains.

**Comment by haz** [comment]
Well it's an old one that wasn't meant to work as well as it did, and has stuck around since! One of the early temporal contest tracks had an entry that just merged the start and end effects (thus having before a delete and add effect of the same fluent). So every durative action was made instantaneous. The approach performed _really_ well, largely due to temporally uninteresting domains, and it was then immortalized in so many of our classical benchmarks.

You're not the first to scratch your head on how it looks (it _is_ weird), and certainly won't be the last :D.
